server:
  port: 8085
  servlet:
    context-path: /notelab-api-v1
    error:
      include-message: always
      include-binding-errors: always
      include-stacktrace:
      include-exception: false

spring:
  application:
    name: notelab

  datasource:
    name: ${DB_NAME:notelab-db}
    host: ${DB_HOST:127.0.0.1}
    username: ${DB_USERNAME:issa}
    password: ${DB_PASSWORD:issa}
    url: jdbc:mysql://${spring.datasource.host}:3306/${spring.datasource.name}?createDatabaseIfNotExist=true

  servlet:
    multipart:
      max-file-size: 30MB
      max-request-size: 30MB

  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      ddl-auto: update
    show-sql: false

springdoc:
  swagger-ui:
    path: /documentation

notelab:
  mail:
    from: 'bankaismash@gmail.com'

storage-document:
  file-storage-root-path: ${user.home}//Documents//upload//notelab
  template-name: template.vm

security-jwt:
  secret-key: MmMzN2VlODJhN2U3NDk2NzQ2ZjE4Nzg3ZDkxYzg5ZDdkZDEwMTdjYWM3OWRiYjQwOWU4M2NiYTdmOThkYTU3OTI3Nzg2YTAwYTc2ODEyMzgwNjhiYTU2MTkyNDNmNWJiODc5Y2M4MWVhNjJhYTU3ZjRmNzEzZDhlZmYxNDlhYWM=
  jwt-expiration: 86400
  refresh-expiration: 2592000

notelab-cors:
  cors:
    allowed-origins: "http://localhost:4200"
    allowed-methods: "GET,POST,PUT,DELETE"
    allowed-headers: "*"
    exposed-headers: "Authorization,Link"
    allow-credentials: true
    max-age: 1800

web:
  url: 'http://localhost:4200/#'